// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<void>;

export function GetNote(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function WalkFrontmatter():Promise<Array<main.Frontmatter>>;
