// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function WalkFrontmatter() {
  return window['go']['main']['App']['WalkFrontmatter']();
}
